### ISSUE TITLE
Only picks up first event

### ISSUE THREAD

**Issue by cknauss** [gkinsman/Serilog.Sinks.EmailPickup#2]
When there is more than one event, only the first one is put in the email and there is only one email.

My config:

 Log.Logger = new LoggerConfiguration()
                                .MinimumLevel.Override("System.Net.Http", LogEventLevel.Warning)
				.Enrich.WithExceptionDetails()
				.WriteTo.Console() 
				.WriteTo.File(
						"Everfi-Upload-.log", 
						rollingInterval:RollingInterval.Hour,
						outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] {Message:lj}  {NewLine}{Exception}")
				.WriteTo.EmailPickup(
					fromEmail: "app@us.edu",
					toEmail:"aaa@def.edu",
					pickupDirectory: @"c:\email",
					subject: "My Exception",
					fileExtension: ".eml" ,
					restrictedToMinimumLevel : LogEventLevel.Information
				)
				.CreateLogger();

Output in log:
[09:43:32 INF] Worker running at: 06/03/2020 09:43:32 -06:00
[09:43:33 INF] Completed uploading 0 total users from 0 files.

Output in email:
To: me@us.edu
From: app@us.edu
Subject: Exception
Date: Wed, 03 Jun 2020 15:49:32 GMT

-----------

Level: Information
Worker running at: 06/03/2020 09:49:32 -06:00

Properties:
time: 06/03/2020 09:49:32 -06:00
SourceContext: "Foundry.Upload.Worker"

No exception was logged

**Comment by gkinsman** [comment]
Hi there, thanks for the report 🙂. 

I'm going to add some tests to make sure nothing is broken long term here, but it looks like you might not be disposing the logger by calling Log.CloseAndFlush.

Since this is a file system IO style sink, the application might be shutting down before the logger gets a chance to write to disk.

Try adding `Log.CloseAndFlush` to the disposal of your worker and see if that works. HTH!

**Comment by cknauss** [comment]
Thank you for your quick response. That did the trick.
I got one email for the first log entry and a second email for the remaining log entries.
